### ISSUE TITLE
Automatically deploy staging when "Publish" is clicked

### ISSUE THREAD

**Issue by daine** [cds-snc/resources-ressources#235]
## 📇 User story

As a content designer, I want to see the published content on the [learning resources staging website](https://staging.learning-resources.cdssandbox.xyz/) as soon as I hit "Publish"

## ✅ Definition of Done
- [x] Webhooks setup in contentful
- [ ] Incoming webhooks setup in AWS Amplify for staging
- [ ] Webhooks in contentful is set to ACTIVE

## 📜 Acceptance criteria
- [ ] Clicking on "Publish" deploys content on the live staging sandbox
- [ ] Amplify webhooks written in terraform

## 🎨 More info
Here's [how to setup incoming webhooks in AWS Amplify
](https://docs.aws.amazon.com/amplify/latest/userguide/webhooks.html
)

I have tested this by doing click-ops and adding a webhook named `contentful-publish`:
<kbd><img width="1408" alt="Screen Shot 2022-08-31 at 4 12 19 PM" src="https://user-images.githubusercontent.com/916044/187800809-889550c7-53cb-4b82-970a-7487aebacca2.png"></kbd>

**TODO**: Terraform that config^^^:
```
resource "aws_amplify_webhook" "main" {
  app_id      = aws_amplify_app.learning_resources.id
  branch_name = aws_amplify_branch.main.branch_name
  description = "contentful-publish"
}
```
---
I have created a contentful webhook for publishing. Here's what the current configuration looks like (it works!):
<kbd><img width="751" alt="Screen Shot 2022-08-31 at 4 14 26 PM" src="https://user-images.githubusercontent.com/916044/187801166-e099f463-656e-4085-b6d5-65bc2c008634.png"></kbd>
**_.....and more configuration....._**
<kbd><img width="723" alt="Screen Shot 2022-08-31 at 4 15 40 PM" src="https://user-images.githubusercontent.com/916044/187801173-5ea2fd2f-e4fa-48f2-9276-c70d10dcfe95.png"></kbd>
---

### How did I confirm that it works? I updated our "Contact Us" page and separated the sentences into a new paragraph (added a new line), and hit "Publish.

**Webhook logs (triggered by hitting "Publish" on an entry)**:
<kbd><img width="894" alt="Screen Shot 2022-08-31 at 4 13 16 PM" src="https://user-images.githubusercontent.com/916044/187800928-1e238681-8366-40bf-8a79-e0741985548f.png"></kbd>

### Confirming that the webhook works on AWS Amplify:
_AWS Amplify redeploying from the contentful webhook trigger_
<kbd><img width="460" alt="Deployment triggered by contentful webhook" src="https://user-images.githubusercontent.com/916044/187801818-14047199-a9ba-4d2d-9fe4-f7d52cec2213.png"></kbd>

### Screenshots of the website before, and after the changes:
**Before deployment:**
<kbd><img width="1272" alt="Learning Resources Contact Us Page Separate Paragraphs" src="https://user-images.githubusercontent.com/916044/187802225-c8e712e2-7643-43e2-8fed-a941dda3af94.png"></kbd>

**After deployment:**
<kbd><img width="1029" alt="Learning Resources Contact Us Page One Paragraph" src="https://user-images.githubusercontent.com/916044/187802271-18719ea3-1d29-4d20-9071-35a0bdf1c593.png"></kbd>

### I have since reverted the change, and **DEACTIVATED** the contentful webhook

**Comment by anikbrazeau** [comment]
I wonder if this also might include a mechanism to control `what's in staging` and `what's in production`? 

> As a content designer, I want to see the content **change** on the [learning resources staging website](https://staging.learning-resources.cdssandbox.xyz/) as soon as I hit "Publish" **or " "Unpublish" in both English and French....and want to control when that content makes it to production**

I'm wondering if there might be a way to remove the automatic redeployment of Contentful content when a PR is merged? Would that help us control resource content more predictably?

**Comment by daine** [comment]
Grooming notes:
This is currently deactivated so it is **not working**
We need to know if this is something we need, could we re-activate it in staging?
Hitting publish would be very similar to committing code, so does a redeployment make sense?
